# Tool pack 2 page definitions (imported by gen_pages.py). Built by Blockchain Lab — https://blockchainlab.com
CHAIN_OPTS = "".join(f'<option value="{k}">{n}</option>' for k,n in [("ethereum","Ethereum"),("base","Base"),("arbitrum","Arbitrum One"),("optimism","OP Mainnet"),("polygon","Polygon PoS"),("bsc","BNB Smart Chain"),("avalanche","Avalanche C-Chain")])
BS_OPTS = "".join(f'<option value="{k}">{n}</option>' for k,n in [("ethereum","Ethereum"),("base","Base"),("arbitrum","Arbitrum One"),("optimism","OP Mainnet"),("polygon","Polygon PoS")])
V3_OPTS = BS_OPTS
P2 = {}
P2["safe"] = ("Safe (Gnosis Safe) multisig tx builder & decoder — safeTxHash, MultiSend | Blockchain Lab Tools",
 "Build a Safe transaction and compute its EIP-712 safeTxHash locally, cross-check against the Safe contract on-chain, read owners/threshold/nonce, and decode execTransaction or MultiSend batches.",
 "Safe multisig tx builder & decoder", "Reads the Safe contract over public RPC; hashes computed locally with ethers.js and cross-checked with the Safe's own <code>getTransactionHash()</code>. Always verify the hash on your hardware wallet screen.",
 [("/learn/concepts/wallet","Wallets"),("/development-lab/smart-contract-security-assurance","Security assurance"),("/learn/concepts/smart-contract","Smart contracts")],
 f'''<div class="card"><h3>1. Safe</h3><div class="row"><div><label>Chain</label><select id="c">{CHAIN_OPTS}</select></div><div style="grid-column:span 2"><label>Safe address</label><input id="safe" placeholder="0x… (your Safe)"></div></div><button id="load">Load owners / threshold / nonce</button><div id="info"></div></div>
<div class="card"><h3>2. Build transaction</h3><div class="row"><div><label>To</label><input id="to" value="0x000000000000000000000000000000000000dEaD"></div><div><label>Value (wei)</label><input id="val" value="0"></div><div><label>Operation</label><select id="op"><option value="0">0 · Call</option><option value="1">1 · DelegateCall</option></select></div><div><label>Nonce</label><input id="nonce" value="0"></div></div><label>Data (hex)</label><textarea id="data">0x</textarea><button id="hash">Compute safeTxHash</button><div id="hout"></div></div>
<div class="card"><h3>3. Decode Safe calldata</h3><label>execTransaction / multiSend / any calldata</label><textarea id="dec"></textarea><button id="dgo">Decode</button><div id="dout"></div></div>''',
 '''const tx=()=>D.safeTx({to:$("#to").value.trim(),value:$("#val").value||0,data:$("#data").value.trim()||"0x",operation:$("#op").value,nonce:$("#nonce").value||0});let info=null;
on("load",async()=>{const o=$("#info");busy(o);try{info=await D.safeInfo($("#c").value,$("#safe").value.trim());$("#nonce").value=info.nonce;o.innerHTML=kv({Version:esc(info.version),Threshold:`${info.threshold} of ${info.owners.length}`,Nonce:info.nonce,Owners:info.owners.map(esc).join("<br>")})}catch(e){fail(o,e)}});
on("hash",async()=>{const o=$("#hout");busy(o);try{const c=$("#c").value,s=$("#safe").value.trim();if(!s)throw new Error("Enter a Safe address first");const t=tx();const id=C.CHAINS[c].id;const l=D.safeTxHash(id,s,t,info?.version||"1.3.0");let onc="(load the Safe to cross-check)";try{const h=await D.safeTxHashOnchain(c,s,t);onc=h===l.safeTxHash?`<span class=ok>✓ matches on-chain getTransactionHash()</span>`:`<span class=err>✗ on-chain ${h}</span>`}catch(e){onc=`<span class=err>${esc(e.message)}</span>`}
 o.innerHTML=kv({"safeTxHash":l.safeTxHash,"Domain separator":l.domainSeparator,"SafeTx struct hash":l.messageHash,"On-chain check":onc,"Decoded data":t.data!=="0x"?esc(JSON.stringify((await D.decodeSafeCalldata(t.data)),(k,v)=>typeof v==="bigint"?v.toString():v).slice(0,800)):"(none)"})}catch(e){fail(o,e)}});
on("dgo",async()=>{const o=$("#dout");busy(o);try{const r=await D.decodeSafeCalldata($("#dec").value.trim());o.innerHTML=`<pre>${esc(JSON.stringify(r,(k,v)=>typeof v==="bigint"?v.toString():v,2))}</pre>`}catch(e){fail(o,e)}});
if(params.get("safe")){$("#safe").value=params.get("safe");if(params.get("chain"))$("#c").value=params.get("chain");document.getElementById("load").click();}
$("#dec").value=D.encodeMultiSend([{to:"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",data:C.encodeCall("approve(address,uint256)",["0x000000000022D473030F116dDEE9F6B43aC78BA3",0n])},{to:"0x000000000000000000000000000000000000dEaD",value:1n}]);''')

P2["eip712"] = ("EIP-712 typed data signer & verifier, EIP-191, ERC-1271 | Blockchain Lab Tools",
 "Hash EIP-712 typed data (digest, domain separator, struct hash), sign with a throwaway key or your wallet, recover the signer, verify personal_sign messages and check ERC-1271 smart-account signatures on-chain.",
 "EIP-712 signer / verifier", "All hashing and recovery runs locally (ethers.js). Never paste a real private key: use the throwaway key or sign with your wallet extension.",
 [("/learn/concepts/wallet","Wallets"),("/learn/concepts/account-abstraction","Account abstraction"),("/learn/glossary","Glossary")],
 f'''<div class="card"><label>Typed data JSON (eth_signTypedData_v4 format)</label><textarea id="td" style="min-height:220px"></textarea><div class="row"><div><button id="h">Hash</button> <button id="sw" class="sec">Sign with wallet</button> <button id="sk" class="sec">Sign with throwaway key</button></div></div><div id="hout"></div></div>
<div class="card"><h3>Verify</h3><label>Signature</label><input id="sig"><button id="v">Recover signer (EIP-712)</button> <div class="row"><div><label>ERC-1271 chain</label><select id="c">{CHAIN_OPTS}</select></div><div style="grid-column:span 2"><label>Smart account address (optional)</label><input id="acct" placeholder="0x…"></div></div><button id="v1271" class="sec">Check ERC-1271 isValidSignature</button><div id="vout"></div></div>
<div class="card"><h3>EIP-191 personal_sign</h3><label>Message</label><input id="msg" value="hello"><label>Signature</label><input id="psig"><button id="pv">Recover</button><div id="pout"></div></div>''',
 '''$("#td").value=JSON.stringify(D.EIP712_MAIL_EXAMPLE,null,1);const td=()=>JSON.parse($("#td").value);
on("h",()=>{const o=$("#hout");try{const h=D.typedDataHash(td());o.innerHTML=kv({"Primary type":h.primaryType,"Digest (sign this)":h.digest,"Domain separator":h.domainSeparator,"Struct hash":h.structHash})}catch(e){fail(o,e)}});
on("sk",async()=>{const o=$("#hout");try{const w=C.ethers.Wallet.createRandom();const s=await D.signTypedData(w.privateKey,td());$("#sig").value=s.signature;o.innerHTML=kv({"Throwaway signer":s.signer,"Signature":s.signature})}catch(e){fail(o,e)}});
on("sw",async()=>{const o=$("#hout");try{if(!window.ethereum)throw new Error("No wallet extension found");const [a]=await window.ethereum.request({method:"eth_requestAccounts"});const sig=await window.ethereum.request({method:"eth_signTypedData_v4",params:[a,JSON.stringify(td())]});$("#sig").value=sig;o.innerHTML=kv({Signer:a,Signature:sig})}catch(e){fail(o,e)}});
on("v",()=>{const o=$("#vout");try{o.innerHTML=kv({"Recovered signer":D.recoverTypedData(td(),$("#sig").value.trim())})}catch(e){fail(o,e)}});
on("v1271",async()=>{const o=$("#vout");busy(o);try{const r=await D.erc1271($("#c").value,$("#acct").value.trim(),D.typedDataHash(td()).digest,$("#sig").value.trim());o.innerHTML=kv({"isValidSignature":r.valid?"<span class=ok>✓ valid (0x1626ba7e)</span>":`<span class=err>✗ ${esc(r.magic||r.error||"invalid")}</span>`})}catch(e){fail(o,e)}});
on("pv",()=>{const o=$("#pout");try{o.innerHTML=kv({"Recovered signer":D.recoverPersonal($("#msg").value,$("#psig").value.trim()),"EIP-191 hash":C.ethers.hashMessage($("#msg").value)})}catch(e){fail(o,e)}});
document.getElementById("h").click();''')

P2["calldiff"] = ("Calldata diff — compare two transactions' calldata field by field | Blockchain Lab Tools",
 "Decode two calldata blobs (or two tx hashes) with openchain/4byte signatures and highlight every argument and 32-byte word that differs.",
 "Calldata diff", "Useful for reviewing multisig proposals, governance payloads and re-submitted transactions. Paste calldata or a tx hash on each side.",
 [("/development-lab/smart-contract-security-assurance","Security assurance"),("/learn/concepts/smart-contract","Smart contracts"),("/learn/failures","Failure classes")],
 f'''<div class="card"><div class="row"><div><label>Chain (for tx hashes)</label><select id="c">{CHAIN_OPTS}</select></div><div><label>Signature hint (optional)</label><input id="sig" placeholder="transfer(address,uint256)"></div></div><div class="row"><div><label>A — calldata or tx hash</label><textarea id="a"></textarea></div><div><label>B — calldata or tx hash</label><textarea id="b"></textarea></div></div><button id="go">Diff</button></div><div id="out" class="card"></div>''',
 '''$("#a").value=C.encodeCall("transfer(address,uint256)",["0x000000000000000000000000000000000000dEaD",1000000n]);$("#b").value=C.encodeCall("transfer(address,uint256)",["0x000000000000000000000000000000000000dEaD",2500000n]);
const resolve=async(x)=>{x=x.trim();if(/^0x[0-9a-fA-F]{64}$/.test(x)){const t=await C.rpc($("#c").value,"eth_getTransactionByHash",[x]);if(!t)throw new Error("tx not found: "+x);return t.input}return x};
on("go",async()=>{const o=$("#out");busy(o);try{const d=await D.calldataDiff(await resolve($("#a").value),await resolve($("#b").value),$("#sig").value.trim()||undefined);
 o.innerHTML=`<p>${d.sameFunction?"Same function":"<span class=err>Different functions</span>"}: A=<b>${esc(d.a.signature||d.a.selector)}</b> B=<b>${esc(d.b.signature||d.b.selector)}</b> · <b>${d.changed}</b> decoded field(s) differ</p>`+table(d.rows,[["Field",r=>esc(r.field)],["A",r=>`<span class="mono ${r.same?"":"err"}">${esc(r.a??"—")}</span>`],["B",r=>`<span class="mono ${r.same?"":"ok"}">${esc(r.b??"—")}</span>`]])+"<h3>Raw 32-byte words</h3>"+table(d.wordDiff,[["Word",r=>r.word],["A",r=>`<span class="mono ${r.same?"mut":"err"}">${esc(r.a??"—")}</span>`],["B",r=>`<span class="mono ${r.same?"mut":"ok"}">${esc(r.b??"—")}</span>`]])}catch(e){fail(o,e)}});document.getElementById("go").click();''')

P2["verify"] = ("Contract verification lookup — Sourcify & Blockscout | Blockchain Lab Tools",
 "Check whether a smart contract's source code is verified on Sourcify (full/partial match) and Blockscout, with compiler version, licence, proxy type and implementation addresses.",
 "Contract verification lookup", "Queries the public <a href='https://sourcify.dev'>Sourcify</a> v2 API and <a href='https://www.blockscout.com/'>Blockscout</a> instances. Unverified code is not necessarily malicious, but you can't read what it does.",
 [("/development-lab/smart-contract-security-assurance","Security assurance"),("/learn/concepts/smart-contract","Smart contracts"),("/learn/failures","Failure classes")],
 f'''<div class="card"><div class="row"><div><label>Chain</label><select id="c">{CHAIN_OPTS}</select></div><div style="grid-column:span 2"><label>Contract address</label><input id="a" value="0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"></div></div><button id="go">Look up</button></div><div id="out" class="card"></div>''',
 '''on("go",async()=>{const o=$("#out");busy(o);try{const v=await D.verification($("#c").value,$("#a").value.trim());const s=v.sourcify,b=v.blockscout;
 o.innerHTML=`<h3>${v.verified?"<span class=ok>✓ Verified source available</span>":"<span class=err>✗ No verified source found</span>"}</h3>`+kv({"Sourcify":s.match?`<b>${esc(s.match)}</b> (creation: ${esc(s.creationMatch)}, runtime: ${esc(s.runtimeMatch)}) · ${esc(s.name||"")} ${esc(s.compiler||"")} · verified ${esc(s.verifiedAt||"")} · <a href="${s.url}">files</a>`:esc(s.note||"not found"),"Blockscout":b.verified?`<b>verified</b> · ${esc(b.name||"")} · ${esc(b.compiler||"")} · licence ${esc(b.license||"n/a")} · optimizer ${b.optimization} · <a href="${b.url}">source</a>`:esc(b.note||"not verified"),"Proxy":b.proxyType?esc(b.proxyType)+" → "+(b.implementations||[]).map(i=>esc(i.address_hash||i.address)+" "+esc(i.name||"")).join(", "):"","Explorer":`<a href="${v.explorer}">${v.explorer}</a>`})}catch(e){fail(o,e)}});
if(params.get("address")){$("#a").value=params.get("address");if(params.get("chain"))$("#c").value=params.get("chain");}document.getElementById("go").click();''')

P2["gas-history"] = ("Gas price history charts — last 1,024 blocks on 7 EVM chains | Blockchain Lab Tools",
 "Chart base fee, median priority tip and block fullness over the last 1,024 blocks for Ethereum, Base, Arbitrum, OP, Polygon, BNB Chain and Avalanche, with min/median/p75/max stats.",
 "Gas history charts", "From <code>eth_feeHistory</code> on public RPCs (up to 1,024 blocks ≈ 3.4 h on Ethereum, ≈ 34 min on Base). Live — no stored data.",
 [("/learn/concepts/rollup","Rollups"),("/intelligence/crypto-pulse","Crypto Pulse"),("/learn/fundamentals","Fundamentals")],
 f'''<div class="card"><div class="row"><div><label>Chain</label><select id="c">{CHAIN_OPTS}</select></div><div><label>Blocks</label><select id="n"><option>1024</option><option>512</option><option>256</option><option>100</option></select></div></div><button id="go">Load</button></div><div id="out" class="card"></div>''',
 '''on("go",async()=>{const o=$("#out");busy(o,"Fetching fee history…");try{const g=await D.gasHistory($("#c").value,Number($("#n").value));const s=g.stats;
 o.innerHTML=`<h3>${esc(C.CHAINS[g.chain].name)} · blocks ${g.from.toLocaleString()}–${g.to.toLocaleString()}</h3>`+kv({"Base fee min / median / p75 / max (gwei)":[s.min,s.median,s.p75,s.max].map(x=>x.toPrecision(4)).join(" / "),"Next block base fee (gwei)":s.nextBaseFeeGwei.toPrecision(4)})+`<p class=mut>Base fee (gwei)</p>${D.sparkSVG(g.points.map(p=>p.baseFeeGwei))}<p class=mut>Median priority tip (gwei)</p>${D.sparkSVG(g.points.map(p=>p.tipP50Gwei),900,120,"#fbbf24")}<p class=mut>Block gas used ratio</p>${D.sparkSVG(g.points.map(p=>p.gasUsedRatio),900,80,"#93c5fd")}`}catch(e){fail(o,e)}});
if(params.get("chain"))$("#c").value=params.get("chain");$("#c").onchange=()=>document.getElementById("go").click();document.getElementById("go").click();''')

P2["bridge"] = ("Bridge fee comparison — Across vs LI.FI vs Relay live quotes | Blockchain Lab Tools",
 "Compare live quotes for bridging USDC or ETH between Ethereum, Base, Arbitrum, OP and Polygon: amount received, fees and estimated time from Across, LI.FI and Relay.",
 "Bridge fee compare", "Live quotes from the public <a href='https://docs.across.to/'>Across</a>, <a href='https://docs.li.fi/'>LI.FI</a> and <a href='https://docs.relay.link/'>Relay</a> APIs for a placeholder address. Quotes move every block; always confirm in the bridge UI. Origin-chain gas is extra unless noted.",
 [("/learn/concepts/bridge","Bridges"),("/learn/concepts/interoperability","Interoperability"),("/learn/failures","Bridge failure classes")],
 f'''<div class="card"><div class="row"><div><label>From</label><select id="f">{BS_OPTS}</select></div><div><label>To</label><select id="t">{BS_OPTS}</select></div><div><label>Asset</label><select id="as"><option>USDC</option><option>ETH</option></select></div><div><label>Amount</label><input id="amt" value="1000"></div></div><button id="go">Get quotes</button></div><div id="out" class="card"></div>''',
 '''$("#t").value="base";on("go",async()=>{const o=$("#out");busy(o,"Requesting quotes…");try{if($("#as").value==="ETH"&&($("#f").value==="polygon"||$("#t").value==="polygon"))throw new Error("ETH route to/from Polygon PoS uses WETH; pick USDC or another chain");const q=await D.bridgeQuotes({from:$("#f").value,to:$("#t").value,asset:$("#as").value,amount:$("#amt").value});const best=Math.max(...q.quotes.filter(x=>x.ok).map(x=>x.out));
 o.innerHTML=table(q.quotes,[["Provider",x=>`<b>${esc(x.provider)}</b>`],["You receive",x=>x.ok?`${x.out.toFixed(q.asset==="USDC"?2:6)} ${q.asset}${x.out===best?' <span class="pill ok">best</span>':""}`:`<span class=err>${esc(x.error)}</span>`],["Cost",x=>x.ok?`${x.cost.toFixed(q.asset==="USDC"?2:6)} ${q.asset} (${(x.cost/q.amount*100).toFixed(3)}%)`:""],["Est. time",x=>x.ok&&x.etaSec!=null?`${x.etaSec}s`:""],["Notes",x=>esc([x.note,x.gasUSD?`gas ≈ $${x.gasUSD.toFixed(2)}`:""].filter(Boolean).join(" · "))]])}catch(e){fail(o,e)}});document.getElementById("go").click();''')

P2["approvals"] = ("Token approval checker & revoke links | Blockchain Lab Tools",
 "Check which popular spenders (Permit2, Uniswap, 1inch, 0x, CoW, Balancer, OpenSea, Aave…) can move an address's ERC-20 tokens, flag unlimited approvals, and get one-click revoke links and approve(spender, 0) calldata.",
 "Token approval checker", "Batch-reads <code>allowance(owner, spender)</code> for the top tokens on the chain × 15 well-known spenders via Multicall3. For a full history scan of every spender, use the <a href='https://revoke.cash'>Revoke.cash</a> link.",
 [("/learn/concepts/wallet","Wallets"),("/learn/failures","Failure classes"),("/development-lab/smart-contract-security-assurance","Security assurance")],
 f'''<div class="card"><div class="row"><div><label>Chain</label><select id="c">{CHAIN_OPTS}</select></div><div style="grid-column:span 2"><label>Owner address or ENS</label><input id="a" value="vitalik.eth"></div></div><button id="go">Check approvals</button></div><div id="out" class="card"></div>''',
 '''on("go",async()=>{const o=$("#out");busy(o,"Reading allowances via Multicall3…");try{let a=$("#a").value.trim();if(a.endsWith(".eth"))a=await C.resolveEns(a);const r=await D.approvals($("#c").value,a);
 o.innerHTML=`<p>${r.approvals.length} live approval(s) across ${r.checkedTokens} tokens × ${r.checkedSpenders} spenders for <span class=mono>${r.owner}</span> · <a href="${r.revokeCash}">Full scan &amp; revoke on Revoke.cash ↗</a></p>`+table(r.approvals,[["Token",x=>`<b>${esc(x.token.symbol)}</b> <span class=mono>${x.token.address}</span>`],["Spender",x=>`${esc(x.spenderName)}<br><span class=mono>${x.spender}</span>`],["Allowance",x=>x.unlimited?'<span class=err>UNLIMITED</span>':esc(C.ethers.formatUnits(x.allowance,x.token.decimals))],["Revoke",x=>`<details><summary>approve(spender, 0) calldata</summary><span class=mono>to ${x.token.address}<br>${x.revokeCalldata}</span></details>`]])}catch(e){fail(o,e)}});
if(params.get("address"))$("#a").value=params.get("address");if(params.get("chain"))$("#c").value=params.get("chain");document.getElementById("go").click();''')

P2["ens-bulk"] = ("ENS bulk resolver — resolve many names & reverse-lookup addresses | Blockchain Lab Tools",
 "Resolve a list of ENS names to addresses (with avatar, url, Twitter, GitHub records) and reverse-resolve addresses to primary names, verifying forward/reverse match. Export as CSV.",
 "ENS bulk resolver", "One name or address per line. Uses the ENS Universal Resolver via public Ethereum RPC; up to 100 entries.",
 [("/learn/concepts/wallet","Wallets"),("/learn/concepts/identity","Identity"),("/learn/glossary","Glossary")],
 '''<div class="card"><label>Names / addresses (one per line)</label><textarea id="q" style="min-height:140px">vitalik.eth
nick.eth
brantly.eth
0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045</textarea><button id="go">Resolve</button> <button id="csv" class="sec">Download CSV</button></div><div id="out" class="card"></div>''',
 '''let last=[];on("go",async()=>{const o=$("#out");busy(o,"Resolving…");try{const qs=$("#q").value.split("\\n").map(s=>s.trim()).filter(Boolean).slice(0,100);last=await D.ensBulk(qs);
 o.innerHTML=table(last,[["Input",x=>esc(x.input)],["Address",x=>x.error?`<span class=err>${esc(x.error)}</span>`:`<span class=mono>${esc(x.address||"—")}</span>`],["Primary name",x=>esc(x.primaryName??x.name??"—")+(x.isPrimary||x.verified?" <span class=ok>✓</span>":"")],["Records",x=>x.texts?Object.entries(x.texts).map(([k,v])=>`${esc(k)}: ${esc(v)}`).join("<br>"):""]])}catch(e){fail(o,e)}});
on("csv",()=>{const rows=[["input","address","primary_name","records"],...last.map(x=>[x.input,x.address||"",x.primaryName||x.name||"",JSON.stringify(x.texts||{})])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(",")).join("\\n")],{type:"text/csv"}));a.download="ens-bulk.csv";a.click();});document.getElementById("go").click();''')

P2["solana-tx"] = ("Solana transaction decoder — instructions, balance & token changes | Blockchain Lab Tools",
 "Decode any Solana transaction signature: status, fee, compute units, parsed instructions and inner instructions with program names (Jupiter, Raydium, Orca, Meteora, SPL Token…), SOL and token balance changes, and logs.",
 "Solana tx decoder", "Uses <code>getTransaction</code> (jsonParsed) on public Solana RPCs. Very old transactions may be pruned by public nodes.",
 [("/learn/protocols","Protocol profiles"),("/learn/compare","Compare designs"),("/learn/concepts/virtual-machine","Virtual machines")],
 '''<div class="card"><label>Transaction signature</label><input id="s" placeholder="5h…"><button id="go">Decode</button> <button id="latest" class="sec">Latest Jupiter swap</button></div><div id="out" class="card"></div>''',
 '''on("go",async()=>{const o=$("#out");busy(o);try{const d=await D.decodeSolTx($("#s").value.trim());history.replaceState(null,"","?sig="+d.signature);
 o.innerHTML=`<h3>${d.status==="success"?"<span class=ok>✓ success</span>":"<span class=err>✗ failed</span>"} <a href="https://solscan.io/tx/${d.signature}">Solscan ↗</a></h3>`+kv({Slot:d.slot,Time:d.blockTime,"Fee":d.feeSOL+" SOL","Compute units":d.computeUnits,Version:esc(d.version),Signers:d.signers.map(esc).join("<br>")})+"<h3>Instructions</h3>"+table(d.instructions,[["Program",x=>`<b>${esc(x.program)}</b>`],["Type",x=>esc(x.type||"")],["Info",x=>x.info?`<span class=mono>${esc(JSON.stringify(x.info).slice(0,300))}</span>`:`${x.accounts??0} accounts`]])+(d.innerInstructions.length?`<h3>Inner instructions (${d.innerInstructions.length})</h3>`+table(d.innerInstructions.slice(0,40),[["Parent #",x=>x.index],["Program",x=>esc(x.program)],["Type",x=>esc(x.type||"")]]):"")+"<h3>Token balance changes</h3>"+table(d.tokenChanges,[["Owner",x=>`<span class=mono>${esc(x.owner)}</span>`],["Mint",x=>`<span class=mono>${esc(x.mint)}</span>`],["Change",x=>`<span class="${x.delta>0?"ok":"err"}">${x.delta>0?"+":""}${x.delta}</span>`]])+"<h3>SOL changes</h3>"+table(d.solChanges,[["Account",x=>`<span class=mono>${esc(x.account)}</span>`],["Δ SOL",x=>x.deltaSOL]])+`<details><summary>Logs</summary><pre>${esc((d.logs||[]).join("\\n"))}</pre></details>`}catch(e){fail(o,e)}});
on("latest",async()=>{const o=$("#out");busy(o);try{const s=await D.solRpc("getSignaturesForAddress",["JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4",{limit:5}]);$("#s").value=(s.find(x=>!x.err)||s[0]).signature;document.getElementById("go").click()}catch(e){fail(o,e)}});
if(params.get("sig")){$("#s").value=params.get("sig");document.getElementById("go").click();}''')

P2["psbt"] = ("Bitcoin PSBT & raw transaction decoder | Blockchain Lab Tools",
 "Decode a Bitcoin PSBT (BIP-174, base64 or hex) or raw transaction: inputs, outputs, addresses, script types, fee and fee rate, signatures present, BIP-32 derivation paths. Runs offline in your browser.",
 "Bitcoin PSBT decoder", "Parsing by <a href='https://github.com/paulmillr/scure-btc-signer'>@scure/btc-signer</a> locally — nothing is broadcast or uploaded. Check the fee and change address before signing.",
 [("/learn/protocols/bitcoin","Bitcoin"),("/learn/concepts/wallet","Wallets"),("/whitepaper","Bitcoin whitepaper")],
 '''<div class="card"><label>PSBT (base64 / hex) or raw transaction hex</label><textarea id="p" style="min-height:120px"></textarea><button id="go">Decode</button> <button id="ex" class="sec">Load BIP-174 test vector</button></div><div id="out" class="card"></div>''',
 '''const sat=(v)=>v==null?"?":`${v.toLocaleString()} sats (${(Number(v)/1e8).toFixed(8)} BTC)`;
on("go",()=>{const o=$("#out");try{const d=D.decodePSBT($("#p").value);o.innerHTML=`<h3>${esc(d.kind)}</h3>`+kv({"Version":d.version,"Locktime":d.locktime,"Inputs total":sat(d.inputTotal),"Outputs total":sat(d.outputTotal),"Fee":d.feeSats!=null?sat(d.feeSats):"unknown (input amounts missing)","vsize":d.vsize??"","Fee rate":d.feeRate!=null?d.feeRate.toFixed(2)+" sat/vB":"","Finalized":d.isFinal,"txid":d.txid||""})+"<h3>Inputs</h3>"+table(d.inputs,[["Outpoint",x=>`<span class=mono>${esc(x.txid)}:${x.vout}</span>`],["Value",x=>sat(x.value)],["Address / type",x=>esc((x.address||"")+" "+(x.type||""))],["Sigs",x=>x.finalized?"final":x.partialSigs],["BIP-32",x=>x.bip32.map(b=>`${b.fingerprint} ${b.path}`).join("<br>")]])+"<h3>Outputs</h3>"+table(d.outputs,[["Address",x=>esc(x.address||"(non-standard)")],["Type",x=>esc(x.type)],["Value",x=>sat(x.value)]])}catch(e){fail(o,e)}});
on("ex",async()=>{const md=await (await C.tfetch("https://raw.githubusercontent.com/bitcoin/bips/master/bip-0174.mediawiki")).text();const sec=md.slice(md.indexOf("The following are valid PSBTs"));$("#p").value=sec.match(/Base64 String: <(?:pre|tt)>(cHNidP8[^<]+)</)[1];document.getElementById("go").click()});
document.getElementById("ex").click();''')

P2["labels"] = ("Address labels — who is this address? Blockscout tags, ENS, OFAC check | Blockchain Lab Tools",
 "Look up public labels for an EVM address: Blockscout contract name and public tags, token info, ENS primary name, Uniswap token-list match, well-known spender names, and an OFAC SDN sanctions check.",
 "Address labels", "Aggregates public sources only. A missing label means nothing either way; a sanctions hit should be confirmed against the official OFAC list.",
 [("/learn/concepts/wallet","Wallets"),("/intelligence","Intelligence"),("/learn/failures","Failure classes")],
 f'''<div class="card"><div class="row"><div><label>Chain</label><select id="c">{BS_OPTS}</select></div><div style="grid-column:span 2"><label>Address</label><input id="a" value="0x000000000022D473030F116dDEE9F6B43aC78BA3"></div></div><button id="go">Look up</button></div><div id="out" class="card"></div>''',
 '''on("go",async()=>{const o=$("#out");busy(o);try{const l=await D.addressLabels($("#c").value,$("#a").value.trim());o.innerHTML=(l.sanctioned?'<h3 class=err>⚠ On the OFAC SDN list</h3>':'<p class=ok>Not on the OFAC SDN digital-currency list (as of last API build)</p>')+kv({"Address":l.address,"Type":l.isContract===undefined?"":l.isContract?"contract":"EOA","Creator":l.creator?esc(l.creator):""})+table(l.labels,[["Source",x=>esc(x.source)],["Label",x=>`<b>${esc(x.label)}</b>`]])}catch(e){fail(o,e)}});
if(params.get("address"))$("#a").value=params.get("address");if(params.get("chain"))$("#c").value=params.get("chain");document.getElementById("go").click();''')

P2["vanity"] = ("Vanity address difficulty & time estimator + CREATE2 calculator | Blockchain Lab Tools",
 "Estimate how many attempts and how long it takes to find an Ethereum vanity address prefix (case-insensitive or EIP-55 checksum), benchmarked live on your device, and compute CREATE2 deployment addresses.",
 "Vanity address estimator", "Benchmark derives real secp256k1 keypairs in your browser. Dedicated GPU tools are ~10⁴–10⁶× faster. Never use a vanity key generated by a website you don't control — and beware the 2022 Profanity weakness.",
 [("/learn/concepts/wallet","Wallets"),("/learn/failures","Failure classes"),("/learn/glossary","Glossary")],
 '''<div class="card"><div class="row"><div><label>Prefix (hex, after 0x)</label><input id="p" value="dead"></div><div><label><input type="checkbox" id="cs" style="width:auto"> case-sensitive (EIP-55)</label></div><div><label>Your GPU rate (keys/s, optional)</label><input id="gpu" value="200000000"></div></div><button id="go">Estimate</button><div id="out"></div></div>
<div class="card"><h3>CREATE2 address</h3><div class="row"><div><label>Deployer</label><input id="d" value="0x4e59b44847b379578588920cA78FbF26c0B4956C"></div><div><label>Salt (number or hex)</label><input id="s" value="0"></div></div><label>Init code (hex)</label><textarea id="ic">0x00</textarea><button id="c2">Compute</button><div id="c2o"></div></div>''',
 '''const dur=(s)=>s<1?"< 1 s":s<120?s.toFixed(0)+" s":s<7200?(s/60).toFixed(1)+" min":s<172800?(s/3600).toFixed(1)+" h":s<63072000?(s/86400).toFixed(1)+" days":(s/31536000).toExponential(2)+" years";
on("go",async()=>{const o=$("#out");busy(o,"Benchmarking your device for 1 s…");await new Promise(r=>setTimeout(r,30));try{const d=D.vanityDifficulty($("#p").value,{caseSensitive:$("#cs").checked});const rate=D.vanityBenchmark(1000);const g=Number($("#gpu").value)||0;
 o.innerHTML=kv({"Difficulty (1 in N)":Math.round(d.difficulty).toLocaleString(),"Attempts for 50% / 90% chance":`${Math.round(d.attempts50).toLocaleString()} / ${Math.round(d.attempts90).toLocaleString()}`,"This browser":`${Math.round(rate).toLocaleString()} keys/s → 50%: ${dur(d.attempts50/rate)}, 90%: ${dur(d.attempts90/rate)}`,"GPU at your rate":g?`50%: ${dur(d.attempts50/g)}, 90%: ${dur(d.attempts90/g)}`:""})}catch(e){fail(o,e)}});
on("c2",()=>{const o=$("#c2o");try{o.innerHTML=kv({"CREATE2 address":D.create2Address($("#d").value.trim(),$("#s").value.trim(),$("#ic").value.trim()),"init code hash":C.ethers.keccak256($("#ic").value.trim())})}catch(e){fail(o,e)}});document.getElementById("c2").click();document.getElementById("go").click();''')

P2["price-impact"] = ("Uniswap v3 price impact calculator — live on-chain quotes | Blockchain Lab Tools",
 "Quote a Uniswap v3 swap on-chain with QuoterV2 and see amount out, mid price, execution price, price impact, price after the trade, ticks crossed and gas estimate — Ethereum, Base, Arbitrum, OP, Polygon.",
 "Uniswap price impact", "Calls the official Uniswap v3 QuoterV2 and pool <code>slot0</code> via public RPC (single pool, no routing). Aggregators may find better multi-pool routes.",
 [("/learn/concepts/amm","AMMs"),("/learn/concepts/defi","DeFi"),("/intelligence/crypto-pulse","Crypto Pulse")],
 f'''<div class="card"><div class="row"><div><label>Chain</label><select id="c">{V3_OPTS}</select></div><div><label>Token in</label><input id="ti"></div><div><label>Token out</label><input id="to"></div><div><label>Fee tier</label><select id="fee"><option value="100">0.01%</option><option value="500" selected>0.05%</option><option value="3000">0.3%</option><option value="10000">1%</option></select></div><div><label>Amount in</label><input id="amt" value="10"></div></div><button id="go">Quote</button> <button id="flip" class="sec">⇄ flip</button></div><div id="out" class="card"></div>''',
 '''const def=()=>{const c=$("#c").value;$("#ti").value=D.WETH[c];$("#to").value=D.USDC[c];};def();$("#c").onchange=def;
on("flip",()=>{const a=$("#ti").value;$("#ti").value=$("#to").value;$("#to").value=a;});
on("go",async()=>{const o=$("#out");busy(o);try{const sizes=[Number($("#amt").value)];const r=await D.priceImpact($("#c").value,$("#ti").value.trim(),$("#to").value.trim(),$("#amt").value,Number($("#fee").value));
 o.innerHTML=kv({"Pool":`<span class=mono>${r.pool}</span>`,"You receive":`<b>${r.amountOut.toLocaleString(undefined,{maximumFractionDigits:6})} ${esc(r.tokenOut)}</b> for ${r.amountIn} ${esc(r.tokenIn)}`,"Mid price":`${r.midPrice.toPrecision(8)} ${esc(r.tokenOut)}/${esc(r.tokenIn)}`,"Execution price":r.execPrice.toPrecision(8),"Price impact (excl. LP fee)":`<b class="${r.priceImpactPct>1?"err":"ok"}">${r.priceImpactPct.toFixed(4)}%</b>`,"Total cost vs mid (incl. fee)":r.totalCostVsMidPct.toFixed(4)+"%","Price after trade":r.priceAfter.toPrecision(8),"Ticks crossed":r.ticksCrossed,"Gas estimate":r.gasEstimate.toLocaleString()})}catch(e){fail(o,e)}});document.getElementById("go").click();''')

P2["mev"] = ("MEV sandwich checker — was my swap sandwiched? | Blockchain Lab Tools",
 "Paste an Ethereum/Base/Arbitrum/OP/Polygon transaction hash to check whether it was sandwiched: finds a front-run swap on the same pool in the same direction and a back-run reversing it from the same EOA or bot contract.",
 "MEV sandwich checker", "Heuristic using <code>eth_getBlockReceipts</code> and Uniswap v2/v3-style Swap events (covers most AMMs that emit them). A positive is strong evidence, not proof; a negative doesn't rule out other MEV.",
 [("/learn/concepts/mev","MEV"),("/learn/failures","Failure classes"),("/learn/concepts/amm","AMMs")],
 f'''<div class="card"><div class="row"><div><label>Chain</label><select id="c">{CHAIN_OPTS}</select></div><div style="grid-column:span 2"><label>Transaction hash</label><input id="h" value="0xe7f3514e534215762a686f2535721c1ec07f95a09548dc669bafb5bc03fce7f4"></div></div><button id="go">Check</button> <button id="scan" class="sec">Scan latest block for sandwiches</button></div><div id="out" class="card"></div>''',
 '''const ex=(c,h)=>`<a href="${C.CHAINS[c].explorer}/tx/${h}">${h.slice(0,14)}…</a>`;
on("go",async()=>{const o=$("#out");busy(o,"Reading block receipts…");try{const c=$("#c").value;const r=await D.sandwichCheck(c,$("#h").value.trim());const e=r.evidence;
 o.innerHTML=`<h3>${r.sandwiched?"<span class=err>⚠ Likely sandwiched</span>":"<span class=ok>No sandwich pattern found</span>"}</h3>`+kv({"Block / index":`${r.block} / ${r.index} of ${r.blockTxs}`,"Swaps in tx":r.swapsInTx,"Front-run":e?`${ex(c,e.front.hash)} idx ${e.front.index} from <span class=mono>${e.front.from}</span>`:"","Back-run":e?`${ex(c,e.back.hash)} idx ${e.back.index} from <span class=mono>${e.back.from}</span>`:"","Pool":e?`<span class=mono>${e.pool}</span>`:"","Bot contract":e?`<span class=mono>${e.front.to}</span>`:"","Method":esc(r.method)})}catch(e){fail(o,e)}});
on("scan",async()=>{const o=$("#out");busy(o,"Scanning…");try{const c=$("#c").value;const b=Number(await C.rpc(c,"eth_blockNumber"))-1;const s=await D.findSandwiches(c,b);o.innerHTML=`<p>Block ${b}: ${s.length} sandwich pattern(s)</p>`+table(s,[["Victim",x=>ex(c,x.victim)],["Front-run",x=>ex(c,x.front)],["Pool",x=>`<span class=mono>${x.pool}</span>`]])}catch(e){fail(o,e)}});
if(params.get("hash")){$("#h").value=params.get("hash");if(params.get("chain"))$("#c").value=params.get("chain");}document.getElementById("go").click();''')

P2["stablecoins"] = ("Stablecoin peg & supply monitor — USDT, USDC, DAI, USDe… | Blockchain Lab Tools",
 "Live stablecoin table: price vs peg, circulating supply, 7-day supply change, peg mechanism and chain count for 400+ stablecoins from DefiLlama.",
 "Stablecoin monitor", "Live from the <a href='https://stablecoins.llama.fi/stablecoins'>DefiLlama stablecoins API</a>. Depeg highlighted when price is more than 0.5% from $1 (USD-pegged only).",
 [("/learn/concepts/stablecoin","Stablecoins"),("/intelligence/stablecoins","Stablecoin intelligence"),("/learn/failures","Failure classes")],
 '''<div class="card"><div class="row"><div><label>Filter</label><input id="q" placeholder="symbol or name"></div><div><label>Peg</label><select id="peg"><option value="">All</option><option value="peggedUSD" selected>USD</option><option value="peggedEUR">EUR</option><option value="peggedVAR">Other</option></select></div></div></div><div id="out" class="card"></div>''',
 '''let all=[];const o=$("#out");busy(o,"Loading…");try{all=await D.stablecoins();render()}catch(e){fail(o,e)}
function render(){const q=$("#q").value.trim().toLowerCase(),p=$("#peg").value;const rows=all.filter(x=>(!p||x.pegType===p)&&(!q||x.symbol.toLowerCase().includes(q)||x.name.toLowerCase().includes(q))).slice(0,100);const tot=rows.reduce((s,x)=>s+x.circulating,0);
 o.innerHTML=`<p class=mut>${rows.length} shown · $${(tot/1e9).toFixed(1)}bn circulating</p>`+table(rows,[["Stablecoin",x=>`<b>${esc(x.symbol)}</b> ${esc(x.name)}`],["Price",x=>x.price==null?"—":`<span class="${x.pegType==="peggedUSD"&&Math.abs(x.price-1)>0.005?"err":""}">$${x.price.toFixed(4)}</span>`],["Circulating",x=>"$"+(x.circulating/1e6).toLocaleString(undefined,{maximumFractionDigits:0})+"m"],["7d",x=>x.change7dPct==null?"":`<span class="${x.change7dPct<0?"err":"ok"}">${x.change7dPct.toFixed(2)}%</span>`],["Mechanism",x=>esc(x.mechanism)],["Chains",x=>x.chains]])}
$("#q").oninput=render;$("#peg").onchange=render;''')

P2["rpc-health"] = ("Public RPC health checker — latency & block lag for free endpoints | Blockchain Lab Tools",
 "Test free public RPC endpoints for Ethereum, Base, Arbitrum, OP, Polygon, BNB Chain and Avalanche from your browser: reachability, latency, chain ID and how many blocks behind the best endpoint each is. Plus the nightly server-side probe.",
 "RPC health checker", "Browser tests are subject to CORS (some endpoints block browsers). The nightly <a href='https://blockchains.github.io/blockchainlab-api/v1/rpc-health.json'>rpc-health dataset</a> probes from GitHub Actions without CORS.",
 [("/learn/fundamentals","Fundamentals"),("/learn/protocol-atlas","Protocol atlas"),("/learn/compare","Compare designs")],
 f'''<div class="card"><div class="row"><div><label>Chain</label><select id="c">{CHAIN_OPTS}</select></div><div style="grid-column:span 2"><label>Extra RPC URLs (one per line, optional)</label><textarea id="x" style="min-height:40px"></textarea></div></div><button id="go">Test from my browser</button></div><div id="out" class="card"></div><div id="srv" class="card"></div>''',
 '''on("go",async()=>{const o=$("#out");busy(o,"Probing…");try{const c=$("#c").value;const extra=$("#x").value.split("\\n").map(s=>s.trim()).filter(Boolean);const h=await D.rpcHealth(c,[...D.PUBLIC_RPCS[c],...extra]);
 o.innerHTML=`<h3>${esc(C.CHAINS[c].name)} · head ${h.head.toLocaleString()} · ${h.endpoints.filter(e=>e.healthy).length}/${h.endpoints.length} healthy</h3>`+table(h.endpoints,[["Endpoint",e=>`<span class=mono>${esc(e.url)}</span>`],["Status",e=>e.healthy?"<span class=ok>✓ healthy</span>":e.ok?`<span class=err>lag ${e.lag}</span>`:`<span class=err>✗ ${esc(e.error)}</span>`],["Latency",e=>e.latencyMs+" ms"],["Block",e=>e.block?.toLocaleString()??""],["Chain ID",e=>e.chainIdOk===false?"<span class=err>wrong</span>":e.chainIdOk?"✓":""]]);
 const s=await C.dataset("rpc-health");const rows=s.data.filter(r=>r.chain===c);$("#srv").innerHTML=`<h3>Server-side probe (${esc(s.generated_at)})</h3>`+table(rows,[["Endpoint",e=>`<span class=mono>${esc(e.url)}</span>`],["Healthy",e=>e.healthy?"<span class=ok>✓</span>":"<span class=err>✗</span>"],["Latency",e=>e.latency_ms!=null?e.latency_ms+" ms":""],["Lag",e=>e.lag_blocks??""]])}catch(e){fail(o,e)}});
$("#c").onchange=()=>document.getElementById("go").click();document.getElementById("go").click();''')
